### ISSUE TITLE
mermaid not working

### ISSUE THREAD

**Issue by guilhermebodin** [bauglir/Kroki.jl#47]
I am having trouble building some documentation that relied on Kroki to render the diagrams.

https://github.com/psrenergy/PSRClassesInterface.jl/actions/runs/7118845881/job/19382649359

This is a bad request somewhere. Anybody happens to know how to fix this?

**Comment by guilhermebodin** [comment]
It does not work in the kroki website 
![image](https://github.com/bauglir/Kroki.jl/assets/32756941/3ee3a870-79b5-4a36-b9b9-b09a59ec989a)

**Comment by bauglir** [comment]
Hi Guilherme! I can reproduce this not working on the Kroki website as well. Unfortunately, that means there is not too much that I can do to alleviate this. This package is just a simple wrapper around the Kroki service hosted on https://kroki.io. In this case it's best to raise this directly with the people hosting the service. Likely through their Zulip chat which already has a few threads[^1][^2] regarding this subject that were active yesterday.

One alternative, that's been on my to-do list to write up for a long time but hasn't bubbled to the top just yet, is to use a locally hosted version of Kroki. See also #43. If you have [Docker Compose](https://docs.docker.com/compose/) installed within your CI environment, you can use [the `Kroki.Service.start!` function](https://bauglir.github.io/Kroki.jl/stable/api/#Kroki.Service.start!) to start a locally running service (for instance in your `docs/make.jl`). After that has been called the package will automatically use that version by default.

[^1]: https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/.E2.9C.94.20kroki.20mermaid.20failing
[^2]: https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/kroki.2Eio.20returns.20400.20on.20Mermaid.20diagrams
